always:
  Resize:
    height: 512
    interpolation: 1
    p: 1.0
    width: 512
pick_randomly:
  GaussianBlur:
    blur_limit:
    - 3
    - 7
    p: 0.5
    sigma_limit:
    - 0.0
    - 0.5
  HorizontalFlip:
    p: 0.5
  Rotate:
    border_mode: 4
    crop_border: false
    interpolation: 1
    limit:
    - -90
    - 90
    mask_value: null
    p: 0.5
    rotate_method: largest_box
  VerticalFlip:
    p: 0.5
